apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  containers:
    - image: mysql
      imagePullPolicy: IfNotPresent
      name: mysql
      envFrom:
      - secretRef:
          name: mysql-secret
      ports:
        - containerPort: 3306
