apiVersion: v1
kind: Pod
metadata:
  labels:
    name: wordpress
  name: wordpress
spec:
  containers:
    - image: wordpress
      imagePullPolicy: IfNotPresent
      name: wordpress
      envFrom:
      - secretRef:
          name: wordpress-secret
      ports:
        - containerPort: 3306
